const { ObjectIds } = require("../../../../src/main/typescript/elvarg/util/IdEnums");
const { Anim } = require("../constants");
const { climb } = require("../steps");

module.exports = {
  key: "pollnivneach",
  name: "Pollnivneach Rooftop",
  lapXp: 890,
  petBase: 33422, // Giant squirrel base chance (Wiki)
  marks: {
    level: 70,
    tiles: [[3346, 2968, 1], [3354, 2974, 1], [3361, 2993, 2]],
  },
  obstacles: [
    {
      object: ObjectIds.BASKET_4,
      index: 1,
      level: 70,
      xp: 10,
      steps: [
        { anim: Anim.JUMP_SHORT },
        { wait: 1 },
        { tele: [3351, 2962, 1] },
        { anim: Anim.LAND },
        { wait: 1 },
        { anim: Anim.JUMP_SHORT },
        { wait: 1 },
        { tele: [3351, 2964, 1] },
        { anim: Anim.LAND },
      ],
    },
    {
      object: ObjectIds.MARKET_STALL_13,
      index: 2,
      level: 70,
      xp: 45,
      route: [3350, 2968, 1],
      steps: [
        { anim: Anim.RUN_UP },
        { wait: 1 },
        { move: [3350, 2971], anim: Anim.JUMP_HURDLE, speed: [0, 45], ticks: 2, dir: "north" },
        { wait: 1 },
        { move: [3352, 2973], anim: Anim.LAND, speed: [0, 30], dir: "north" },
      ],
    },
    {
      object: ObjectIds.BANNER_13,
      index: 3,
      level: 70,
      xp: 65,
      route: [3354, 2976, 1],
      steps: [
        { anim: Anim.RUN_UP },
        { wait: 1 },
        { anim: -1 },
        { move: [3357, 2977, 2], speed: [0, 30], dir: "north" },
        { anim: Anim.HANG },
        { wait: 2 },
        { move: [3360, 2977, 1], anim: Anim.LAND, speed: [0, 30], dir: "north" },
      ],
    },
    {
      object: ObjectIds.GAP_30,
      index: 4,
      level: 70,
      xp: 35,
      route: [3362, 2977, 1],
      steps: [
        { move: [3365, 2976, 2], speed: [0, 30], dir: "east" },
        { anim: Anim.GRAB_LEDGE },
        { wait: 2 },
        { tele: [3366, 2976, 1] },
      ],
    },
    {
      object: ObjectIds.TREE_53,
      index: 5,
      level: 70,
      xp: 75,
      route: [3368, 2976, 1],
      steps: [
        { move: [3368, 2978, 2], speed: [0, 30], dir: "east" },
        { anim: Anim.HANG_SWING },
        { wait: 1 },
        { move: [3368, 2980, 2], speed: [0, 30], dir: "east" },
        { anim: Anim.HANG_SWING_QUICK },
        { wait: 1 },
        { move: [3368, 2982, 1], anim: Anim.LAND, speed: [0, 30], dir: "east" },
        { faceDir: "north" },
      ],
    },
    {
      object: ObjectIds.ROUGH_WALL_5,
      index: 6,
      level: 70,
      xp: 5,
      steps: [{ faceDir: "north" }, ...climb([3365, 2983, 2])],
    },
    {
      object: ObjectIds.MONKEYBARS,
      index: 7,
      level: 70,
      xp: 55,
      route: [3358, 2984, 2],
      steps: [
        { anim: Anim.MONKEY_BARS_JUMP },
        { wait: 1 },
        { render: Anim.MONKEY_BARS_CROSS },
        { walk: [[3358, 2991]] },
        { render: null },
        { anim: Anim.MONKEY_BARS_DROP },
      ],
    },
    {
      object: ObjectIds.TREE_126,
      index: 8,
      level: 70,
      xp: 60,
      route: [3360, 2995, 2],
      steps: [
        { move: [3360, 2997], anim: Anim.JUMP_HURDLE, speed: [0, 30], dir: "north" },
        { move: [3359, 3000], anim: Anim.JUMP_HURDLE, speed: [0, 30], dir: "north" },
      ],
    },
    {
      object: ObjectIds.DRYING_LINE,
      index: 9,
      level: 70,
      xp: 540,
      route: [3362, 3002, 2],
      steps: [
        { move: [3363, 3000], anim: Anim.JUMP, speed: [0, 30], dir: "south" },
        { anim: Anim.LEAP },
        { wait: 1 },
        { tele: [3363, 2998, 0] },
        { anim: Anim.LAND },
      ],
    },
  ],
};
