// Reports how close the RuneLite-shaped API is to the ../runelite checkout:
// implemented events, injectable services and per-plugin missing dependencies.
// Writes docs/runelite-api-coverage.md.
//
//   client/node_modules/.bin/tsx scripts/runelite-api-coverage.ts
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const runelite = join(root, "..", "runelite");
const runeliteApi = join(runelite, "runelite-api", "src", "main", "java", "net", "runelite", "api");
const runeliteClient = join(runelite, "runelite-client", "src", "main", "java", "net", "runelite", "client");
const output = join(root, "docs", "runelite-api-coverage.md");

if (!existsSync(runeliteApi)) {
    console.error(`runelite-api-coverage: ${runeliteApi} not found (expected a ../runelite checkout)`);
    process.exit(1);
}

function javaClassNames(dir: string): string[] {
    return readdirSync(dir)
        .filter((file) => file.endsWith(".java"))
        .map((file) => file.replace(/\.java$/, ""));
}

function implementedEvents(): Set<string> {
    const dir = join(root, "client", "runelite", "api", "events");
    const index = readFileSync(join(dir, "index.ts"), "utf8");
    const names = new Set<string>();
    for (const match of index.matchAll(/^\s{4}(\w+),$/gm)) names.add(match[1]);
    return names;
}

function boundServices(): Set<string> {
    // Tokens provided by RuneLite.start / PluginManager.
    return new Set(["Client", "ConfigManager", "EventBus", "PluginManager", "OverlayManager", "ItemManager"]);
}

function clientMethods(): Set<string> {
    // The Client facade is not built yet (plan §4.4); no methods are declared.
    return new Set<string>();
}

const allEvents = javaClassNames(join(runeliteApi, "events"));
const events = implementedEvents();
const services = boundServices();
const methods = clientMethods();

type PluginReport = {
    name: string;
    events: string[];
    services: string[];
    methods: string[];
};

function analysePlugin(dir: string, name: string): PluginReport {
    let source = "";
    const walk = (path: string): void => {
        for (const entry of readdirSync(path, { withFileTypes: true })) {
            if (entry.isDirectory()) walk(join(path, entry.name));
            else if (entry.name.endsWith(".java")) source += readFileSync(join(path, entry.name), "utf8");
        }
    };
    walk(dir);

    const requiredEvents = new Set<string>();
    for (const match of source.matchAll(/import net\.runelite\.api\.events\.(\w+);/g)) {
        requiredEvents.add(match[1]);
    }
    const requiredServices = new Set<string>();
    for (const match of source.matchAll(/@Inject\s+(?:private|protected|public)?\s*[\w<>,. ]+?\s+(\w+);/g)) {
        requiredServices.add(match[1]);
    }
    const requiredMethods = new Set<string>();
    for (const match of source.matchAll(/\bclient\.(\w+)\s*\(/g)) {
        requiredMethods.add(match[1]);
    }

    return {
        name,
        events: [...requiredEvents].filter((event) => !events.has(event)),
        services: [...requiredServices].filter((service) => !services.has(service) && !service.endsWith("config")),
        methods: [...requiredMethods].filter((method) => !methods.has(method)),
    };
}

const pluginRoot = join(runeliteClient, "plugins");
const reports: PluginReport[] = [];
for (const entry of readdirSync(pluginRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    reports.push(analysePlugin(join(pluginRoot, entry.name), entry.name));
}

const portable = reports.filter((report) => report.events.length === 0 && report.services.length === 0 && report.methods.length === 0);

const lines: string[] = [
    "# RuneLite API coverage",
    "",
    "Generated by `scripts/runelite-api-coverage.ts` against `../runelite`.",
    "The `Client` facade and the actor/overlay/menu APIs are phase 2+ work",
    "(plan §4.4-4.9), so the portable-now count stays at zero until those land.",
    "",
    "## Summary",
    "",
    `- Events: ${events.size}/${allEvents.length} implemented`,
    `- Plugins analysed: ${reports.length}`,
    `- Plugins portable now: ${portable.length}`,
    "",
    "## Events",
    "",
    `Implemented: ${[...events].sort().join(", ") || "(none)"}`,
    "",
    `Missing: ${allEvents.filter((event) => !events.has(event)).sort().join(", ")}`,
    "",
    "## Plugins",
    "",
    "| Plugin | Missing events | Missing services | Missing client methods |",
    "|---|---|---|---|",
];

for (const report of reports.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(
        `| ${report.name} | ${report.events.join(", ") || "-"} | ${report.services.join(", ") || "-"} | ${report.methods.join(", ") || "-"} |`,
    );
}
lines.push("");

writeFileSync(output, lines.join("\n"));
console.log(`runelite-api-coverage: wrote ${output} (${portable.length}/${reports.length} portable now)`);
