// Generates ./plugins/skills/farming/farmingPatchValues.js from RuneLite's
// PatchImplementation.java (BSD-2-Clause) so the plugin can turn crop state into the
// cache varbit values the client renders patches with.
//
//   npx ts-node ./scripts/generate-farming-patch-values.ts [path-to-PatchImplementation.java]
//
// The Java file is fetched from the RuneLite repo when no path is passed.
import * as fs from "fs";
import * as path from "path";

const SUPPORTED = new Set([
    "ALLOTMENT", "FLOWER", "HERB", "HOPS", "BUSH", "TREE", "FRUIT_TREE",
    "SPIRIT_TREE", "CACTUS", "MUSHROOM", "BELLADONNA", "CALQUAT", "COMPOST",
]);

type Range = { from: number; to: number; produce: string; state: string; stage: string };

async function loadSource(): Promise<string> {
    const file = process.argv[2];
    if (file) return fs.readFileSync(path.resolve(file), "utf8");
    const response = await fetch(
        "https://raw.githubusercontent.com/runelite/runelite/master/runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/PatchImplementation.java",
    );
    if (!response.ok) throw new Error(`fetch failed: ${response.status}`);
    return response.text();
}

function parse(source: string): Map<string, Range[]> {
    const lines = source.split(/\r?\n/);
    const result = new Map<string, Range[]>();
    let current: string | null = null;
    let pending: { from: number; to: number } | null = null;
    const conditional = /if \(value (>= (\d+) && value <= (\d+)|== (\d+))\)/;
    const patchState = /return new PatchState\(Produce\.([A-Z_]+), CropState\.([A-Z_]+), (.+?)\);/;
    for (const line of lines) {
        const enumMatch = /^\t([A-Z_]+)\(Tab\./.exec(line);
        if (enumMatch) {
            current = enumMatch[1];
            continue;
        }
        const ifMatch = conditional.exec(line);
        if (ifMatch && current) {
            pending = ifMatch[2] !== undefined
                ? { from: Number(ifMatch[2]), to: Number(ifMatch[3]) }
                : { from: Number(ifMatch[4]), to: Number(ifMatch[4]) };
            continue;
        }
        const stateMatch = patchState.exec(line);
        if (stateMatch && current && pending) {
            let stage = stateMatch[3].trim();
            stage = stage.replace(/Produce\.([A-Z_]+)\.getStages\(\) - 1/, "stages-1");
            if (/^-?\d+$/.test(stage)) stage = `const:${stage}`;
            else if (/^value - \d+$/.test(stage)) stage = `value-minus:${stage.slice("value - ".length)}`;
            else if (/^\d+ - value$/.test(stage)) stage = `minus-value:${stage.slice(0, stage.indexOf(" "))}`;
            else if (/^\d+ \+ value$/.test(stage)) stage = `plus-value:${stage.slice(0, stage.indexOf(" "))}`;
            else if (/^value \+ \d+$/.test(stage)) stage = `value-plus:${stage.slice("value + ".length)}`;
            else {
                const shifted = /^(\d+) \+ value - (\d+)$/.exec(stage);
                if (shifted) {
                    const offset = Number(shifted[2]) - Number(shifted[1]);
                    stage = `value-minus:${offset}`;
                }
            }
            if (SUPPORTED.has(current)) {
                const ranges = result.get(current) ?? [];
                ranges.push({ from: pending.from, to: pending.to, produce: stateMatch[1], state: stateMatch[2], stage });
                result.set(current, ranges);
            }
            pending = null;
        }
    }
    return result;
}

async function main() {
    const parsed = parse(await loadSource());
    const out: string[] = [];
    out.push("// Generated by scripts/generate-farming-patch-values.ts from RuneLite's");
    out.push("// PatchImplementation.java (BSD-2-Clause, https://github.com/runelite/runelite).");
    out.push("// Maps a patch type's varbit value ranges to produce/crop state/stage so the");
    out.push("// plugin can resolve the value the client needs. Do not edit by hand.");
    out.push("");
    out.push("module.exports = Object.freeze({");
    for (const type of [...parsed.keys()].sort()) {
        const ranges = parsed.get(type)!;
        out.push(`  ${type}: [`);
        for (const r of ranges) {
            out.push(`    { from: ${r.from}, to: ${r.to}, produce: ${JSON.stringify(r.produce)}, state: ${JSON.stringify(r.state)}, stage: ${JSON.stringify(r.stage)} },`);
        }
        out.push("  ],");
    }
    out.push("});");
    out.push("");
    const destination = path.resolve(__dirname, "..", "plugins", "skills", "farming", "farmingPatchValues.js");
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, out.join("\n"));
    for (const [type, ranges] of parsed) {
        console.log(`${type}: ${ranges.length} ranges`);
    }
    console.log(`wrote ${destination}`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
