// Generates ./plugins/skills/farming/farmingPatchPlacements.js: every map tile an
// object id from the patch catalog occupies, with its loc shape/rotation, so the
// plugin can send per-player loc add/remove packets when a patch changes state.
//
//   npx ts-node ./scripts/generate-farming-placements.ts
import * as fs from "fs";
import * as path from "path";
import { CachePipeline } from "../src/main/typescript/elvarg/game/cache/CachePipeline";
import { CacheMaps } from "../src/main/typescript/elvarg/game/cache/CacheMaps";
import { RegionManager } from "../src/main/typescript/elvarg/game/collision/RegionManager";
import { MapObjects } from "../src/main/typescript/elvarg/game/entity/impl/object/MapObjects";

type Placement = [number, number, number, number, number];

async function main() {
    const patchesModule = require("../plugins/skills/farming/farmingPatches.js");
    const byId = new Map<number, Array<{ key: string; bbox: number[]; z: number }>>();
    for (const patch of patchesModule.PATCHES) {
        const list = byId.get(patch.id) ?? [];
        list.push({ key: patch.key, bbox: patch.bbox, z: patch.z });
        byId.set(patch.id, list);
    }

    await CachePipeline.initialize(path.resolve(__dirname, ".."));
    RegionManager.init();

    const seen = new Set<string>();
    const placements = new Map<string, Placement[]>();
    for (const regionId of CacheMaps.getRegionIds()) {
        const absX = ((regionId >> 8) & 0xff) * 64 + 32;
        const absY = (regionId & 0xff) * 64 + 32;
        const before = MapObjects.mapObjects.size;
        RegionManager.loadMapFiles(absX, absY, false);
        if (before === MapObjects.mapObjects.size) continue;
        for (const list of MapObjects.mapObjects.values()) {
            for (const object of list) {
                const id = object.getId();
                const candidates = byId.get(id);
                if (!candidates) continue;
                const location = object.getLocation();
                const x = location.getX();
                const y = location.getY();
                const z = location.getZ();
                const dedupe = `${id}:${x}:${y}:${z}:${object.getType()}:${object.getFace()}`;
                if (seen.has(dedupe)) continue;
                seen.add(dedupe);
                const patch = candidates.find((candidate) => {
                    if (candidate.z !== z) return false;
                    const [x0, y0, x1, y1] = candidate.bbox;
                    return x >= x0 && x <= x1 && y >= y0 && y <= y1;
                });
                if (!patch) continue;
                const list = placements.get(patch.key) ?? [];
                list.push([x, y, z, object.getType(), object.getFace()]);
                placements.set(patch.key, list);
            }
        }
    }

    const lines = [
        "// Generated by scripts/generate-farming-placements.ts. Do not edit by hand.",
        "// patch key -> [x, y, z, type, face] for every loc tile of the patch.",
        "module.exports = Object.freeze({",
    ];
    for (const key of [...placements.keys()].sort()) {
        const list = placements.get(key)!;
        lines.push(`  ${JSON.stringify(key)}: [${list.map((p) => `[${p.join(", ")}]`).join(", ")}],`);
    }
    lines.push("});", "");
    const destination = path.resolve(__dirname, "..", "plugins", "skills", "farming", "farmingPatchPlacements.js");
    fs.writeFileSync(destination, lines.join("\n"));
    let total = 0;
    for (const list of placements.values()) total += list.length;
    console.log(`patches with placements: ${placements.size}, placements: ${total}`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
